config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  
  resources :car_categories, only: [:index, :show, :new, :create]
  
  resources :subsidiaries, only: [:index, :show]
  
  resources :car_models, only: [:index, :show, :new, :create]
  
  resources :rentals, only: [:index, :show, :new, :create] do
    resources :car_rentals, only: [:new, :create]
    get 'search', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index show create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :car_model
  belongs_to :subsidiary
  has_many :car_rentals

  validates :license_plate, :color, presence: true

  enum status: {available: 0, rented: 10}

  def description
    "#{car_model.name} - #{color} - #{license_plate}"
  end
end

app/models/car_category.rb
class CarCategory < ApplicationRecord
  has_many :car_models
  has_many :cars, through: :car_models

  validates :name, :daily_rate, :car_insurance, 
            :third_party_insurance, presence: true
  validates :name, uniqueness: { case_sensitive: false }

  def daily_price
    daily_rate + car_insurance + third_party_insurance
  end
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :car_category
  has_many :cars

  validates :name, :year, :manufacturer, :fuel_type,
            :motorization, presence: true
end

app/models/car_rental.rb
class CarRental < ApplicationRecord
  belongs_to :rental
  belongs_to :car
  belongs_to :user
end

app/models/customer.rb
class Customer < ApplicationRecord
  def information
    "#{name} - #{cpf}"
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :customer
  belongs_to :car_category
  belongs_to :user
  has_one :car_rental

  before_create :generate_token

  validates :start_date, :end_date, presence: true

  def total
    total_rental_days = end_date - start_date
    total_rental_days * car_category.daily_price
  end

  private

  def generate_token
    self.token = SecureRandom.alphanumeric(6).upcase
  end
end

app/models/subsidiary.rb
class Subsidiary < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :registerable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_many :rentals
  has_many :car_rentals
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found
  rescue_from ActiveRecord::RecordInvalid, with: :render_record_invalid

  private

  def render_not_found(exception)
    render status: :not_found,
           json: "#{controller_name
                      .classify
                      .constantize
                      .model_name
                      .human} não encontrado(a)"
  end

  def render_record_invalid(exception)
    render status: :unprocessable_entity,
           json: exception.message
  end
end

app/controllers/api/v1/cars_controller.rb
class Api::V1::CarsController < Api::V1::ApiController

  def index
    render json: Car.available, status: 200
  end
  def show
    @car = Car.find(params[:id])
    # return render json: @car if @car
    # render status: :not_found, json: ''
    render json: @car
  end

  def create
    @car = Car.create(car_params)
    @car.save!
    render status: :created, json: @car
  
  rescue ActionController::ParameterMissing
    render status: :precondition_failed, json: 'Parâmetros inválidos'
  end

  private

  def car_params
    params.require(:car)
          .permit(:license_plate, :color, :mileage, :car_model_id, :subsidiary_id)
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :create]

  def index
    @car_categories = CarCategory.all
  end
  def show
    @car_category = CarCategory.find(params[:id])
  end
  def new
    @car_category = CarCategory.new
  end
  def create
    @car_category = CarCategory.new(car_category_params)
    if @car_category.save
      redirect_to @car_category
    else
      render :new 
    end
  end

  private

  def car_category_params
    params.require(:car_category)
          .permit(:name, :daily_rate, :car_insurance, :third_party_insurance)
  end
end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  def index
    @car_models = CarModel.all
  end
  
  def show
    @car_model = CarModel.find(params[:id])
  end
  
  def new
    @car_model = CarModel.new
    @car_categories = CarCategory.all
  end
  
  def create
    @car_model = CarModel.new(car_model_params)
    if @car_model.save
      redirect_to @car_model
    else
      @car_categories = CarCategory.all
      render :new
    end
  end
  
  def car_model_params
    params.require(:car_model)
          .permit(:name, :year, :manufacturer, :motorization,
                  :fuel_type, :car_category_id)
  end
end

app/controllers/car_rentals_controller.rb
class CarRentalsController < ApplicationController
  def new
    @rental = Rental.find(params[:rental_id])
    # @available_cars = Car.where(car_model: @rental.car_category.car_models)
    @available_cars = @rental.car_category.cars.available
    @car_rental = CarRental.new
  end

  def create
    @rental = Rental.find(params[:rental_id])
    @car_rental = @rental.build_car_rental(car_rental_params)
    @car_rental.save
    @car_rental.car.rented!
    redirect_to @rental, notice: 'Locação iniciada com sucesso'
  end

  private
  def car_rental_params
    params.require(:car_rental).permit(:car_id, :driver_license_number)
                               .merge({user_id: current_user.id, start_date: Time.zone.now})
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!
  def index
    # @rentals = Rental.all
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def new
    @rental = Rental.new
    @customers = Customer.all
    @car_categories = CarCategory.all
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    if @rental.save
      redirect_to @rental, notice: 'Agendamento realizado com sucesso!'
    else
      @customers = Customer.all
      @car_categories = CarCategory.all
      render :new
    end
  end

  def search
    @rentals = Rental.where('token LIKE UPPER(?)', "%#{params[:q]}%")
    render :index
  end

  private

  def rental_params
    params.require(:rental)
          .permit(:start_date, :end_date, :customer_id, :car_category_id)
  end
end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  def index
    @subsidiaries = Subsidiary.all
  end
  def show
    @subsidiary = Subsidiary.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/car_categories/index.html.erb
<%= link_to 'Voltar', root_path %>

<%= link_to 'Registrar uma nova categoria', new_car_category_path %>

<div>
    <% @car_categories.each do |category| %>
        <%= link_to category.name, category %>
    <% end %>

    <% if @car_categories.empty? %>
        <h3> Nenhuma categoria cadastrada </h3>
    <%end %>
</div>

app/views/car_categories/new.html.erb
<% @car_category.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>
<div>
    <%= form_with model: @car_category, local: true do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :daily_rate %>
        <%= f.number_field :daily_rate %>
    </div>
    <div>
        <%= f.label :car_insurance %>
        <%= f.number_field :car_insurance %>
    </div>
    <div>
        <%= f.label :third_party_insurance %>
        <%= f.number_field :third_party_insurance %>
    </div>
    <%= f.submit 'Enviar' %>
    <% end %>
</div>

app/views/car_categories/show.html.erb
<%= link_to 'Voltar', car_categories_path %>

<h1><%= @car_category.name %></h1>
<dl>
    <dt><%= CarCategory.human_attribute_name(:daily_rate) %></dt>
    <dd><%= number_to_currency @car_category.daily_rate %></dd>
    <dt><%= CarCategory.human_attribute_name(:car_insurance) %></dt>
    <dd><%= number_to_currency @car_category.car_insurance  %></dd>
    <dt><%= CarCategory.human_attribute_name(:third_party_insurance) %></dt>
    <dd><%= number_to_currency @car_category.third_party_insurance %></dd>
</dl> 

app/views/car_models/index.html.erb
<%= link_to 'Voltar', root_path %>
<%= link_to 'Registrar um modelo de carro', new_car_model_path %>

<h1>Modelos de carro</h1>
<% @car_models.each do |car_model|%>
    <div>
        <%= link_to "#{car_model.name} - #{car_model.year}", car_model %>
        <ul>
            <li><%= car_model.manufacturer %></li>
            <li><%= car_model.year %></li>
            <li><%= link_to car_model.car_category.name, car_category_path(car_model.car_category.id) %></li>
        </ul>
    </div>
<% end %>
<% if @car_models.empty? %>
    <h2>Nenhum modelo cadastrado</h2>
<% end %>

app/views/car_models/new.html.erb
<% @car_model.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: @car_model, local: true do |f| %>
  <div>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div>
    <%= f.label :year %>
    <%= f.number_field :year, max: (Date.current.year + 1), min: (Date.current.year - 10) %>
    </div>
    <div>
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
    </div>
    <div>
    <%= f.label :motorization %>
    <%= f.text_field :motorization %>
    </div>
    <div>
    <%= f.label :car_category_id %>
    <%= f.collection_select(:car_category_id, @car_categories, :id, :name, prompt:'Escolha uma categoria de carro' ) %>
    </div>
    <div>
    <%= f.label :fuel_type %>
    <%= f.text_field :fuel_type %>
    </div>
    <%= f.submit "Enviar" %>
  </div>
<% end %>

app/views/car_models/show.html.erb
<h1><%= @car_model.name %></h1>
<dl>
    <dt><%= CarModel.human_attribute_name(:year) %></dt>
    <dd><%= @car_model.year %></dd>
    <dt><%= CarModel.human_attribute_name(:manufacturer) %></dt>
    <dd><%= @car_model.manufacturer  %></dd>
    <dt><%= CarModel.human_attribute_name(:motorization) %></dt>
    <dd><%= @car_model.motorization %></dd>
    <dt><%= CarModel.human_attribute_name(:car_category) %></dt>
    <dd><%= link_to @car_model.car_category.name, car_category_path(@car_model.car_category.id) %></dd>
    <dt><%= CarModel.human_attribute_name(:fuel_type) %></dt>
    <dd><%= @car_model.fuel_type %></dd>
</dl> 

app/views/car_rentals/new.html.erb
<h1>Retirada de Carro</h1>
<h2>Dados do Agendamento</h2>
<%= render @rental %>

<h2>Preencha os campos abaixo para confirmar o início da locação</h2>
<%= form_with model: [@rental, @car_rental], local: true do |f| %>
  <div>
    <%= f.label :car_id, 'Carros disponíveis' %>
    <%= f.collection_select :car_id, @available_cars, :id, :description, prompt: 'Selecione o carro'%>
  </div>
  <div>
    <%= f.label :driver_license_number, 'CNH do Condutor' %>
    <%= f.text_field :driver_license_number %>
  </div>
  <%= f.submit 'Iniciar' %>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
    <%= current_user.name %>
    <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to 'Entrar', new_user_session_path %>
<% end %>

<header>
    <h1>Rental Cars</h1>
    <h2>Bem vindo ao sistema de gestão de locação</h2>
</header>

<%= link_to "Categorias", car_categories_path %>
<%= link_to "Filiais", subsidiaries_path %>
<%= link_to "Modelos de carro", car_models_path %>
<% if user_signed_in? %>
    <%= link_to "Locações", rentals_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalCars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/rentals/_rental.html.erb
<div>
    <dl>
        <dt><%= Rental.human_attribute_name(:token) %></dt>
        <dd><%= rental.token %></dd>
        <dt><%= Rental.human_attribute_name(:start_date) %></dt>
        <dd><%= l rental.start_date %></dd>
        <dt><%= Rental.human_attribute_name(:end_date) %></dt>
        <dd><%= l rental.end_date %></dd>
        <dt><%= Rental.human_attribute_name(:car_category) %></dt>
        <dd><%= rental.car_category.name %></dd>
        <dt> Previsão de valor </dt>
        <dd><%= number_to_currency rental.total %></dd>
        <dt><%= Rental.human_attribute_name(:customer) %></dt>
        <dd><%= rental.customer.name %></dd>
        <dt><%= Customer.human_attribute_name(:cpf) %></dt>
        <dd><%= rental.customer.cpf %></dd>
        <dt><%= Customer.human_attribute_name(:email) %></dt>
        <dd><%= rental.customer.email %></dd>
        <dt><%= Rental.human_attribute_name(:user) %></dt>
        <dd><%= rental.user.name %></dd>
        <dt><%= User.human_attribute_name(:email) %></dt>
        <dd><%= rental.user.email %></dd>
    </dl>
    <%= link_to 'Ver detalhes', rental %>
</div>

app/views/rentals/index.html.erb
<%= link_to 'Agendar nova locação', new_rental_path %>

<%= form_with url: search_rentals_path, method: :get, local: true do |f| %>
  <%= f.label :q, 'Busca de locação' %>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<% if @rentals.present? %>
  <%= render @rentals %>
<% end %>

app/views/rentals/new.html.erb
<% @rental.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: @rental, local: true do |f| %>
    <div>
        <%= f.label :start_date %>
        <%= f.date_field :start_date %>
    </div>
    <div>
        <%= f.label :end_date %>
        <%= f.date_field :end_date %>
    </div>
    <div>
        <%= f.label :customer_id %>
        <%= f.collection_select :customer_id, @customers, :id, :information, prompt: 'Escolha o cliente' %>
    </div>
    <div>
        <%= f.label :car_category_id %>
        <%= f.collection_select :car_category_id, @car_categories, :id, :name, prompt: 'Escolha uma categoria de carro' %>
    </div>
    <%= f.submit 'Agendar' %>
<% end %>

app/views/rentals/show.html.erb
<h1> Locação </h1>

<h2>Dados do Agendamento</h2>
<div>
  <dl>
    <dt>Token</dt>
    <dd><%= @rental.token %></dd>
    <dt>Data de início</dt>
    <dd><%= l @rental.start_date %></dd>
    <dt>Data de término</dt>
    <dd><%= l @rental.end_date %></dd>
    <dt>Cliente</dt>
    <dd><%= @rental.customer.name %></dd>
    <dd><%= @rental.customer.cpf %></dd>
    <dd><%= @rental.customer.email %></dd>
    <dt>Categoria de carro</dt>
    <dd><%= @rental.car_category.name %></dd>
    <dt>Previsão de valor</dt>
    <dd><%= number_to_currency @rental.total %></dd>
    <dt>Usuário</dt>
    <dd><%= @rental.user.email %></dd>
  </dl>
</div>

<% if @rental.car_rental %>
  <h2>Locação Iniciada</h2>

  Carro Escolhido: <%= @rental.car_rental.car.description %>

  CNH do Condutor: <%= @rental.car_rental.driver_license_number %>

  Usuário: <%= @rental.car_rental.user.email %>

  Início da Locação: <%= l @rental.car_rental.start_date %>

  <p>Em andamento</p>

<% else %>

  <%= link_to 'Iniciar locação', new_rental_car_rental_path(@rental.id) %>

<% end %>

app/views/subsidiaries/index.html.erb
<div>
    <% @subsidiaries.each do |subsidiary| %>
        <%= link_to subsidiary.name, subsidiary %>
    <% end %>
</div>

app/views/subsidiaries/show.html.erb
<h1><%= @subsidiary.name %></h1>

<dl>
<dt><%= Subsidiary.human_attribute_name(:CNPJ) %></dt>
<dd><%= @subsidiary.CNPJ %></dd>
<dt><%= Subsidiary.human_attribute_name(:address) %></dt>
<dd><%= @subsidiary.address %></dd>
</dl>